basePath: /
consumes:
- application/json
definitions:
  ErrResponse:
    description: ErrResponse 用来返回错误消息的结构
    properties:
      code:
        format: int64
        type: integer
        x-go-name: Code
      message:
        type: string
        x-go-name: Message
      reference:
        type: string
        x-go-name: Reference
      requestId:
        type: string
        x-go-name: RequestId
    type: object
    x-go-package: github.com/xiaodulala/admin-layout/pkg/httpresponse
  PassWord:
    description: PassWord 密码
    properties:
      newPassword:
        type: string
        x-go-name: NewPassword
      oldPassword:
        type: string
        x-go-name: OldPassword
    type: object
    x-go-package: github.com/xiaodulala/admin-layout/internal/application/sys/service/dto
  ResetSysUserPwdReq:
    properties:
      createBy:
        format: int64
        type: integer
        x-go-name: CreateBy
      password:
        type: string
        x-go-name: Password
      updateBy:
        format: int64
        type: integer
        x-go-name: UpdateBy
      userId:
        format: int64
        type: integer
        x-go-name: UserId
    type: object
    x-go-package: github.com/xiaodulala/admin-layout/internal/application/sys/service/dto
  Response:
    properties:
      data:
        type: object
        x-go-name: Data
      requestId:
        type: string
        x-go-name: RequestId
    type: object
    x-go-package: github.com/xiaodulala/admin-layout/pkg/httpresponse
  RoleDataScopeReq:
    description: RoleDataScopeReq 角色数据权限修改
    properties:
      dataScope:
        type: string
        x-go-name: DataScope
      deptIds:
        items:
          format: int64
          type: integer
        type: array
        x-go-name: DeptIds
      roleId:
        format: int64
        type: integer
        x-go-name: RoleId
    type: object
    x-go-package: github.com/xiaodulala/admin-layout/internal/application/sys/service/dto
  SysApi:
    properties:
      action:
        type: string
        x-go-name: Action
      createBy:
        format: int64
        type: integer
        x-go-name: CreateBy
      createdAt:
        format: date-time
        type: string
        x-go-name: CreatedAt
      handle:
        type: string
        x-go-name: Handle
      id:
        format: int64
        type: integer
        x-go-name: Id
      path:
        type: string
        x-go-name: Path
      title:
        type: string
        x-go-name: Title
      type:
        type: string
        x-go-name: Type
      updateBy:
        format: int64
        type: integer
        x-go-name: UpdateBy
      updatedAt:
        format: date-time
        type: string
        x-go-name: UpdatedAt
    type: object
    x-go-package: github.com/xiaodulala/admin-layout/internal/application/sys/models
  SysDept:
    properties:
      children:
        items:
          $ref: '#/definitions/SysDept'
        type: array
        x-go-name: Children
      createBy:
        format: int64
        type: integer
        x-go-name: CreateBy
      createdAt:
        format: date-time
        type: string
        x-go-name: CreatedAt
      dataScope:
        type: string
        x-go-name: DataScope
      deptId:
        format: int64
        type: integer
        x-go-name: DeptId
      deptName:
        type: string
        x-go-name: DeptName
      deptPath:
        type: string
        x-go-name: DeptPath
      email:
        type: string
        x-go-name: Email
      leader:
        type: string
        x-go-name: Leader
      params:
        type: string
        x-go-name: Params
      parentId:
        format: int64
        type: integer
        x-go-name: ParentId
      phone:
        type: string
        x-go-name: Phone
      sort:
        format: int64
        type: integer
        x-go-name: Sort
      status:
        format: int64
        type: integer
        x-go-name: Status
      updateBy:
        format: int64
        type: integer
        x-go-name: UpdateBy
      updatedAt:
        format: date-time
        type: string
        x-go-name: UpdatedAt
    type: object
    x-go-package: github.com/xiaodulala/admin-layout/internal/application/sys/models
  SysDeptInsertReq:
    properties:
      DeptId:
        format: int64
        type: integer
      createBy:
        format: int64
        type: integer
        x-go-name: CreateBy
      deptName:
        type: string
        x-go-name: DeptName
      deptPath:
        type: string
        x-go-name: DeptPath
      email:
        type: string
        x-go-name: Email
      leader:
        type: string
        x-go-name: Leader
      parentId:
        format: int64
        type: integer
        x-go-name: ParentId
      phone:
        type: string
        x-go-name: Phone
      sort:
        format: int64
        type: integer
        x-go-name: Sort
      status:
        format: int64
        type: integer
        x-go-name: Status
      updateBy:
        format: int64
        type: integer
        x-go-name: UpdateBy
    type: object
    x-go-package: github.com/xiaodulala/admin-layout/internal/application/sys/service/dto
  SysMenu:
    properties:
      RoleId:
        format: int64
        type: integer
      action:
        type: string
        x-go-name: Action
      apis:
        items:
          format: int64
          type: integer
        type: array
        x-go-name: Apis
      breadcrumb:
        type: string
        x-go-name: Breadcrumb
      children:
        items:
          $ref: '#/definitions/SysMenu'
        type: array
        x-go-name: Children
      component:
        type: string
        x-go-name: Component
      createBy:
        format: int64
        type: integer
        x-go-name: CreateBy
      createdAt:
        format: date-time
        type: string
        x-go-name: CreatedAt
      dataScope:
        type: string
        x-go-name: DataScope
      icon:
        type: string
        x-go-name: Icon
      is_select:
        type: boolean
        x-go-name: IsSelect
      isFrame:
        type: string
        x-go-name: IsFrame
      menuId:
        format: int64
        type: integer
        x-go-name: MenuId
      menuName:
        type: string
        x-go-name: MenuName
      menuType:
        type: string
        x-go-name: MenuType
      noCache:
        type: boolean
        x-go-name: NoCache
      params:
        type: string
        x-go-name: Params
      parentId:
        format: int64
        type: integer
        x-go-name: ParentId
      path:
        type: string
        x-go-name: Path
      paths:
        type: string
        x-go-name: Paths
      permission:
        type: string
        x-go-name: Permission
      sort:
        format: int64
        type: integer
        x-go-name: Sort
      sysApi:
        items:
          $ref: '#/definitions/SysApi'
        type: array
        x-go-name: SysApi
      title:
        type: string
        x-go-name: Title
      updateBy:
        format: int64
        type: integer
        x-go-name: UpdateBy
      updatedAt:
        format: date-time
        type: string
        x-go-name: UpdatedAt
      visible:
        type: string
        x-go-name: Visible
    type: object
    x-go-package: github.com/xiaodulala/admin-layout/internal/application/sys/models
  SysRoleDeleteReq:
    properties:
      ids:
        items:
          format: int64
          type: integer
        type: array
        x-go-name: Ids
    type: object
    x-go-package: github.com/xiaodulala/admin-layout/internal/application/sys/service/dto
  SysRoleInsertReq:
    properties:
      Admin:
        type: boolean
      DataScope:
        type: string
      DeptIds:
        items:
          format: int64
          type: integer
        type: array
      Flag:
        type: string
      MenuIds:
        items:
          format: int64
          type: integer
        type: array
      Remark:
        type: string
      RoleId:
        format: int64
        type: integer
      RoleKey:
        type: string
      RoleName:
        type: string
      RoleSort:
        format: int64
        type: integer
      Status:
        type: string
      SysDept:
        items:
          $ref: '#/definitions/SysDept'
        type: array
      SysMenu:
        items:
          $ref: '#/definitions/SysMenu'
        type: array
      createBy:
        format: int64
        type: integer
        x-go-name: CreateBy
      updateBy:
        format: int64
        type: integer
        x-go-name: UpdateBy
    type: object
    x-go-package: github.com/xiaodulala/admin-layout/internal/application/sys/service/dto
  SysRoleUpdateReq:
    properties:
      Admin:
        type: boolean
      DataScope:
        type: string
      DeptIds:
        items:
          format: int64
          type: integer
        type: array
      Flag:
        type: string
      MenuIds:
        items:
          format: int64
          type: integer
        type: array
      Remark:
        type: string
      RoleId:
        format: int64
        type: integer
      RoleKey:
        type: string
      RoleName:
        type: string
      RoleSort:
        format: int64
        type: integer
      Status:
        type: string
      SysDept:
        items:
          $ref: '#/definitions/SysDept'
        type: array
      SysMenu:
        items:
          $ref: '#/definitions/SysMenu'
        type: array
      createBy:
        format: int64
        type: integer
        x-go-name: CreateBy
      updateBy:
        format: int64
        type: integer
        x-go-name: UpdateBy
    type: object
    x-go-package: github.com/xiaodulala/admin-layout/internal/application/sys/service/dto
  SysUserInsertReq:
    properties:
      avatar:
        type: string
        x-go-name: Avatar
      createBy:
        format: int64
        type: integer
        x-go-name: CreateBy
      deptId:
        format: int64
        type: integer
        x-go-name: DeptId
      email:
        type: string
        x-go-name: Email
      nickName:
        type: string
        x-go-name: NickName
      password:
        type: string
        x-go-name: Password
      phone:
        type: string
        x-go-name: Phone
      postId:
        format: int64
        type: integer
        x-go-name: PostId
      remark:
        type: string
        x-go-name: Remark
      roleId:
        format: int64
        type: integer
        x-go-name: RoleId
      sex:
        type: string
        x-go-name: Sex
      status:
        type: string
        x-go-name: Status
      updateBy:
        format: int64
        type: integer
        x-go-name: UpdateBy
      userId:
        format: int64
        type: integer
        x-go-name: UserId
      username:
        type: string
        x-go-name: Username
    type: object
    x-go-package: github.com/xiaodulala/admin-layout/internal/application/sys/service/dto
  SysUserUpdateReq:
    properties:
      avatar:
        type: string
        x-go-name: Avatar
      createBy:
        format: int64
        type: integer
        x-go-name: CreateBy
      deptId:
        format: int64
        type: integer
        x-go-name: DeptId
      email:
        type: string
        x-go-name: Email
      nickName:
        type: string
        x-go-name: NickName
      phone:
        type: string
        x-go-name: Phone
      postId:
        format: int64
        type: integer
        x-go-name: PostId
      remark:
        type: string
        x-go-name: Remark
      roleId:
        format: int64
        type: integer
        x-go-name: RoleId
      sex:
        type: string
        x-go-name: Sex
      status:
        type: string
        x-go-name: Status
      updateBy:
        format: int64
        type: integer
        x-go-name: UpdateBy
      userId:
        format: int64
        type: integer
        x-go-name: UserId
      username:
        type: string
        x-go-name: Username
    type: object
    x-go-package: github.com/xiaodulala/admin-layout/internal/application/sys/service/dto
  UpdateStatusReq:
    properties:
      RoleId:
        format: int64
        type: integer
      Status:
        type: string
      createBy:
        format: int64
        type: integer
        x-go-name: CreateBy
      updateBy:
        format: int64
        type: integer
        x-go-name: UpdateBy
    type: object
    x-go-package: github.com/xiaodulala/admin-layout/internal/application/sys/service/dto
  UpdateSysUserStatusReq:
    properties:
      createBy:
        format: int64
        type: integer
        x-go-name: CreateBy
      status:
        type: string
        x-go-name: Status
      updateBy:
        format: int64
        type: integer
        x-go-name: UpdateBy
      userId:
        format: int64
        type: integer
        x-go-name: UserId
    type: object
    x-go-package: github.com/xiaodulala/admin-layout/internal/application/sys/service/dto
host: localhost:9099
info:
  title: admin-layout  Server API.
  version: 1.0.0
paths:
  /api/v1/sys/dept:
    delete:
      description: 删除部门
      operationId: sysDeptDelete
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/SysRoleDeleteReq'
      responses: {}
      tags:
      - 系统部门管理
    get:
      description: 分页查询部门
      operationId: sysDeptGetPage
      parameters:
      - in: query
        name: deptName
        type: string
        x-go-name: DeptName
      - in: query
        name: deptId
        type: string
        x-go-name: DeptId
      - in: query
        name: position
        type: string
        x-go-name: Position
      responses: {}
      tags:
      - 系统部门管理
    post:
      description: 添加部门
      operationId: sysDeptInsert
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/SysDeptInsertReq'
      responses: {}
      tags:
      - 系统部门管理
    put:
      description: 修改部门
      operationId: sysDeptUpdate
      parameters:
      - format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: Id
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/SysRoleUpdateReq'
      responses: {}
      tags:
      - 系统部门管理
  /api/v1/sys/dept/{deptId}:
    get:
      description: 获取部门数据
      operationId: sysDeptGet
      parameters:
      - in: path
        name: deptId
        required: true
        type: string
        x-go-name: DeptId
      responses: {}
      tags:
      - 系统部门管理
  /api/v1/sys/dept/dept-tree:
    get:
      description: 用户管理左侧部门树
      operationId: sysDeptTree
      responses: {}
      tags:
      - 系统部门管理
  /api/v1/sys/role:
    delete:
      description: 删除角色
      operationId: sysRoleDelete
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/SysRoleDeleteReq'
      responses: {}
      tags:
      - 系统角色管理
    get:
      description: 分页查询角色
      operationId: sysRoleGetPage
      parameters:
      - in: query
        name: roleName
        type: string
        x-go-name: RoleName
      - in: query
        name: status
        type: string
        x-go-name: Status
      - in: query
        name: roleKey
        type: string
        x-go-name: RoleKey
      - format: int64
        in: query
        name: pageSize
        type: integer
        x-go-name: PageSize
      - format: int64
        in: query
        name: pageIndex
        type: integer
        x-go-name: PageIndex
      responses: {}
      tags:
      - 系统角色管理
    post:
      description: 创建角色
      operationId: sysRoleInsert
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/SysRoleInsertReq'
      responses: {}
      tags:
      - 系统角色管理
    put:
      description: 更新角色
      operationId: sysRoleUpdate
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/SysRoleUpdateReq'
      responses: {}
      tags:
      - 系统角色管理
  /api/v1/sys/role-scope:
    put:
      description: 更新角色数据权限
      operationId: sysRoleUpdateDataScope
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/RoleDataScopeReq'
      responses: {}
      tags:
      - 系统角色管理
  /api/v1/sys/role-status:
    put:
      description: 更新角色状态
      operationId: sysRoleUpdateStatue
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/UpdateStatusReq'
      responses: {}
      tags:
      - 系统角色管理
  /api/v1/sys/role/{roleId}:
    get:
      description: 查询角色信息
      operationId: sysRoleGet
      parameters:
      - in: path
        name: roleId
        required: true
        type: string
        x-go-name: RoleId
      responses: {}
      tags:
      - 系统角色管理
  /api/v1/sys/user:
    get:
      description: 分页查询用户
      operationId: sysUserGetPage
      parameters:
      - in: query
        name: username
        type: string
        x-go-name: Username
      responses: {}
      tags:
      - 系统用户管理
    post:
      description: 创建用户
      operationId: sysUserInsert
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/SysUserInsertReq'
      responses: {}
      tags:
      - 系统用户管理
    put:
      description: 更新用户
      operationId: sysUserUpdate
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/SysUserUpdateReq'
      responses: {}
      tags:
      - 系统用户管理
  /api/v1/sys/user/{userId}:
    delete:
      description: 删除用户
      operationId: sysUserDelete
      parameters:
      - in: path
        name: userId
        required: true
        type: string
        x-go-name: UserId
      responses: {}
      tags:
      - 系统用户管理
    get:
      description: 查询用户
      operationId: sysUserGet
      parameters:
      - in: path
        name: userId
        required: true
        type: string
        x-go-name: UserId
      responses: {}
      tags:
      - 系统用户管理
  /api/v1/sys/user/avatar:
    post:
      description: 修改用户头像
      operationId: sysUserAvatar
      responses: {}
      tags:
      - 系统用户管理
  /api/v1/sys/user/profile:
    get:
      description: 获取用户个人中心
      operationId: 系统用户管理
      responses: {}
  /api/v1/sys/user/pwd/reset:
    put:
      description: 重置密码
      operationId: sysUserPwdReset
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/ResetSysUserPwdReq'
      responses: {}
      tags:
      - 系统用户管理
  /api/v1/sys/user/pwd/set:
    put:
      description: 修改密码
      operationId: sysUserPwdSet
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/PassWord'
      responses: {}
      tags:
      - 系统用户管理
  /api/v1/sys/user/status:
    put:
      description: 修改用户状态
      operationId: sysUserStatus
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/UpdateSysUserStatusReq'
      responses: {}
      tags:
      - 系统用户管理
produces:
- application/json
responses:
  errResponse:
    description: ""
    schema:
      $ref: '#/definitions/ErrResponse'
  successResponse:
    description: ""
    schema:
      $ref: '#/definitions/Response'
schemes:
- http
- https
securityDefinitions:
  api_key:
    in: header
    name: Authorization
    type: apiKey
  basic:
    type: basic
swagger: "2.0"
